apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: quizstar-portal
  labels:
    deployment: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: nginx
  template:
    metadata:
      labels:
        pod: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-volume-mount
          mountPath: /app
      volumes:
      - name: app-volume-mount
        persistentVolumeClaim:
          claimName: app-pvc
