apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: quizstar-portal
spec:
  type: LoadBalancer
  selector:
    pod: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
