kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role
rules:
- apiGroups: ["*"] # apps, batch, "" indicates the core API Group
  resources: ["*"] # pods, configmaps, secrets, services, deployments, pods/log, endpointslices, crontabs, jobs, nodes
  verbs: ["*"] # get, watch, list, update, create, patch, delete
