name: Continuous Deployment to Container Apps

env:
  ACR_LOGIN_SERVER: <acr-login-server>
  ACR_NAMESPACE: <acr-namespace>
  ACR_REPOSITORY_NAME: <acr-repository-name>
  ACR_IMAGE_TAG: ${{ github.sha }}
  
  RESOURCE_GROUP_NAME: <resource-group-name>
  CONTAINER_APP_ENVIRONMENT_NAME: <container-apps-environment-name>
  CONTAINER_APP_NAME: <container-app-name>

on:
  # push:
  #   branches:
  #   - master
  #   # paths:
  #   # - app/*
  workflow_dispatch:

jobs:
  build:
    name: Continuous Deployment to Container Apps
    runs-on: ubuntu-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: ${{ env.RESOURCE_GROUP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        imageToDeploy: ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_NAMESPACE }}/${{ env.ACR_REPOSITORY_NAME }}:${{ env.ACR_IMAGE_TAG }}
