services:
  otel-collector:
    container_name: otel-collector-container
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver

  zipkin:
    container_name: zipkin-container
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411

  jaeger:
    container_name: jaeger-container
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp # UDP port for Jaeger agent
      - 16686:16686 # Web UI
      - 14268:14268 # HTTP port for spans

  prometheus:
    container_name: prometheus-container
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090