global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9090']

  # Scrape Zipkin's Prometheus metrics
  - job_name: "zipkin"
    static_configs:
      - targets: ["zipkin:9411"]

  # Optional: Scrape metrics from your application (if you're using Prometheus exporters)
  - job_name: "app"
    static_configs:
      - targets: ["app:8000"]
