apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-appgw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-appgw
  template:
    metadata:
      labels:
        app: ingress-appgw
    spec:
      containers:
      - name: appgwingress
        image: mcr.microsoft.com/cosmosdb/kubernetes-ingress-azure-appgw:1.5
        env:
        # This value must match the name of the AKS cluster
        - name: APPGW_RESOURCE_GROUP
          value: my-aks-cluster-rg
        # This value must match the name of the Application Gateway
        - name: APPGW_NAME
          value: myaksgateway
        # This value must match the name of the AKS cluster
        - name: APPGW_SUBSCRIPTION_ID
          value: <your-subscription-id>
