apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  # namespace: 
  labels:
    deployment: app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: app
  template:
    metadata:
      labels:
        pod: app
    spec:
      restartPolicy: Always
      containers:
      - name: app-container
        image: 
        imagePullPolicy: Never
        ports:
        - containerPort: 
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
