name: Continuous Integration with ECR

env:
  AWS_REGION: <aws-region>
  # ROLE_TO_ASSUME: <arn:aws:iam::123456789012:role/my-github-actions-role>
  ECR_REPOSITORY_NAME: <ecr-repository-name>
  ECR_IMAGE_TAG: ${{ github.sha }}

on:
  # push:
  #   branches:
  #   - master
  #   # paths:
  #   # - app/*
  workflow_dispatch:

jobs:
  build:
    name: Build and push the docker image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        # role-to-assume: ROLE_TO_ASSUME
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2
      # with:
      #   registry-type: public

    - name: Build and push the image
      uses: docker/build-push-action@v5
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
      with:
        context: .
        push: true
        tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_NAME }}:${{ env.ECR_IMAGE_TAG }}