name: Continuous Deployment to EKS

env:
  AWS_REGION: <aws-region>
  ECR_REGISTRY_URI: <ecr-registry-uri>  
  ECR_REPOSITORY_NAME: <ecr-repository-name>
  ECR_IMAGE_TAG: ${{ github.sha }}
  EKS_CLUSTER_NAME: <eks-cluster-name>

on:
  # push:
  #   branches:
  #   - master
  #   # paths:
  #   # - app/*
  workflow_dispatch:

jobs:
  build:
    name: Continuous Deployment to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ env.AWS_REGION }}
        # role-to-assume: ROLE_TO_ASSUME
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Deploy to EKS
      run: |
        sed -i.bak "s|DOCKER_IMAGE|${{ env.ECR_REGISTRY_URI }}/${{ env.ECR_REPOSITORY_NAME }}:${{ env.ECR_IMAGE_TAG }}|g" ./kubernetes/app/deployment.yml && \
        kubectl apply -f ./kubernetes/app/deployment.yml