apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  # namespace:
  labels:
    deployment: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: mongo
  template:
    metadata:
      labels:
        pod: mongo
    spec:
      restartPolicy: Always
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: mongo-configmap
        - secretRef:
            name: mongo-secrets
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvc
