apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  # namespace:
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/docker/db
