apiVersion: apps/v1
kind: Deployment
metadata:
  name: beat-deployment
  # namespace:
  labels:
    deployment: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-beat
  template:
    metadata:
      labels:
        pod: celery-beat
    spec:
      restartPolicy: Always
      containers:
      - name: celery-beat-container
        image: celery:latest
        imagePullPolicy: Never
        command: ['celery', '-A', 'core', 'beat', '-l', 'DEBUG']
        envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: secret
        volumeMounts:
        - name: mount-volume
          mountPath: /app
      volumes:
      - name: mount-volume
        persistentVolumeClaim:
          claimName: pvc
