apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  # namespace:
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      restartPolicy: Always
      containers:
      - name: celery-worker-container
        image: celery:latest
        imagePullPolicy: Never
        command: ['celery', '-A', 'core', 'worker', '-l', 'INFO']
        envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: secret
        volumeMounts:
        - name: volume-mount
          mountPath: /app
      volumes:
      - name: volume-mount
        persistentVolumeClaim:
          claimName: pvc
