apiVersion: v1
kind: Service
metadata:
  name: app-service
  # namespace:
spec:
  type: LoadBalancer # ClusterIP, NodePort, LoadBalancer
  selector:
    pod: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
