apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: shala-app-hpa
#  namespace: shala
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shala-app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
