name: CD to AKS

env:
  ACR_LOGIN_SERVER: <acr-login-server>
  ACR_IMAGE_NAME: <acr-image-name>
  ACR_IMAGE_TAG: ${{ github.sha }}
  
  RESOURCE_GROUP_NAME: <resource-group-name>
  AKS_CLUSTER_NAME: <aks-cluster-name>

on:
  # push:
  #   branches:
  #   - master
  #   # paths:
  #   # - app/*
  workflow_dispatch:

jobs:
  build:
    name: CD to AKS
    runs-on: ubuntu-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        # client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set context to AKS cluster
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ env.RESOURCE_GROUP_NAME }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    - name: Create k8s secret
      uses: azure/k8s-create-secret@v4
      with:
        secret-name: k8s-secret
        # namespace: ''
        container-registry-url: ${{ env.ACR_LOGIN_SERVER }}
        container-registry-username: ${{ secrets.ACR_USERNAME }}
        container-registry-password: ${{ secrets.ACR_PASSWORD }}

    - name: Deploy to AKS cluster
      uses: azure/k8s-deploy@v5
      with:
        # namespace: ''
        manifests: |
          <deployment.yml file location>
        images: |
          ${{ env.ACR_LOGIN_SERVER }}/${{ env.ACR_IMAGE_NAME }}:${{ env.ACR_IMAGE_TAG }}
        imagepullsecrets: |
          k8s-secret