apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  # namespace:
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
