apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  # namespace: 
spec:
  ingressClassName: nginx
  rules:
    - host: host-name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-name
                port:
                  number: 80